[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  nnoremap <silent> ,r :Denite file_mru<CR>
  nnoremap <silent> ,f :Denite file_rec<CR>
  call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>', 'noremap')
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#sources#clang#libclang_path='/usr/lib/llvm-3.8/lib/libclang.so.1'
  let g:deoplete#sources#clang#clang_header='/usr/lib/llvm-3.8/lib/clang/3.8.1/include'
  let g:deoplete#auto_complete_delay=100
  let g:deoplete#enable_at_startup=1
'''

[[plugins]]
repo = 'Rip-Rip/clang_complete'
hook_add = '''
  let g:clang_complete_auto = 0
  let g:clang_auto_select = 0
  let g:clang_omnicppcomplete_compliance = 0
  let g:clang_make_default_keymappings = 0
  let g:clang_library_path='/usr/lib/llvm-3.8/lib/libclang.so.1'
'''
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['Shougo/neosnippet-snippets']
hook_add = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_event = 'InsertEnter'
lazy = 1

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'kana/vim-smartinput'
on_event = 'InsertEnter'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  nnoremap <silent> <leader>t :TagbarToggle<CR>
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'mattn/gist-vim'
lazy = 1

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = 'markdown'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/syntastic'
on_event = 'InsertEnter'

[[plugins]]
repo = 'thiblahute/vim-devhelp'
hook_add = '''
  let g:devhelpSearch=1
'''
on_ft = ['c', 'h', 'cpp']

[[plugins]]
repo = 'tpope/vim-abolish'
lazy = 1

[[plugins]]
repo = 'tpope/vim-endwise'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tpope/vim-rails'
depends = ['tpope/vim-surround']
hook_add = '''
  let g:surround_{char2nr('-')} = "<% \r %>"
  let g:surround_{char2nr('=')} = "<%= \r %>"
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-projectionist'

[[plugins]]
repo = 'camthompson/vim-ember'
depends = ['tpope/vim-projectionist']

[[plugins]]
repo = 'AndrewRadev/ember_tools.vim'
depends = ['tpope/vim-projectionist']

[[plugins]]
repo = 'mustache/vim-mustache-handlebars'

[[plugins]]
repo = 'vim-scripts/gtk-vim-syntax'

[[plugins]]
repo = 'vimwiki/vimwiki'

[[plugins]]
repo = 'vivien/vim-linux-coding-style'
hook_add = '''
  let g:linuxsty_patterns = [ "/usr/src/", "/linux" ]
'''
on_path = [ "/usr/src/", "/linux" ]

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'scss'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  set background=dark
  au VimEnter * nested colorscheme gruvbox
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'python-mode/python-mode'
hook_add = '''
  let g:pymode_python = 'python3'
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

[[plugins]]
repo = 'zenbro/mirror.vim'
